server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:loans;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
      hibernate.jdbc.time_zone: UTC
  flyway:
    enabled: false
  kafka:
    bootstrap-servers: 127.0.0.1:9099

outbox:
  enabled: false

kafka:
  topics:
    auto-create: false

logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info

