server:
  port: ${PORT:8081}

spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/loans}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.jdbc.time_zone: UTC
  flyway:
    enabled: true
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

kafka:
  topics:
    auto-create: true

loan:
  approval:
    threshold: ${LOAN_APPROVAL_THRESHOLD:10000}

outbox:
  polling:
    interval: ${OUTBOX_POLL_INTERVAL:1000}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env

logging:
  pattern:
    level: "%5p [${spring.application.name:loan-api}] traceId=%X{trace_id:-} spanId=%X{span_id:-} %c{1} - %m%n"
